#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf /home/komo/.config/waybar/style/style$SWITCHTO.css /home/komo/.config/waybar/style.css

#change the background image and be cool about it ;)
swaybg -i ~/Wallpaper/wallpaper$SWITCHTO.jpg

#restart the waybar
killall waybar; waybar

